# Book settings
title: Repositorio de LCA
author: equipo docente LCA
logo: _static/logo-uniandes.png

repository:
  url: https://github.com/copa-uniandes/LCA-web-tutorials
  path_to_book: LCA-book
  branch: main

launch_buttons:
  binderhub_url: false
  thebe: true

latex:
  latex_documents:
    targetname: book.tex

html:
  favicon: _static/icon.png
  home_page_in_navbar: false
  use_repository_button: true
  use_issues_button: true
  extra_navbar: "" #Removes 'Powered by Jupyter Book' from left navbar.

myst_enable_extensions:
    - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution

execute:
  execute_notebooks: 'off'
