name: Pull changes and deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

# This job updates the repos dependency on upstream LCA-mini.
jobs:
  update-submodule:
    name: Update LCA mini
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checkout this repo
      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      
      # Update upstream dependencies to latest commit
      - name: Update submodules
        run: |
          git pull --recurse-submodules
          
      # A user is needed por pushing the update. If no changes are detected, nothing gets pushed.
      - name: Push
        run: |
          git config user.name "Alejandro Mantilla"
          git config user.email alejandromantillaredondo@gmail.com
          git add .
          git diff --staged --quiet || (git commit -m "Updated submodules." && git push)
  
  # This job executes all notebooks, builds the book and publishes it to gh-pages
  deploy-book:
    name: Build and publish book
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checkout this repo
    - uses: actions/checkout@v3
    # Checkout upstream jupyter content (replaces LCA-mini, only for build)
    - uses: actions/checkout@v3
      with:
        repository: copa-uniandes/Laboratorio-Computacional-de-Analytics
        token: ${{ secrets.ACCESS_TOKEN }}
        path: PAD-book/Laboratorio-Computacional-de-Analytics

    # Install python and book dependencies
    - name: Set up Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: ./PAD-book/build-environment.yml
        environment-name: JBookEnv
        cache-env: true


    # Deletes all notebooks that are not of type TUTORIAL and are not of type LECTURA
    # Removes all markdown files that are not the book intro
    - name: Remove unused notebooks and md files for book build
      run: |
        find . -name '*.ipynb' ! -name 'TUTORIAL*' ! -name 'LECTURA*' -type f -delete
        find . -name '*.md' ! -name 'intro.md' -type f -delete

    # Build the book, requires bash to initialize autorun scripts for mamba, hence bash -l {0}
    - name: Build the book
      shell: bash -l {0}
      run: |
        jupyter-book build --all ./PAD-book

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./PAD-book/_build/html/

